#!/usr/bin/env bash

"${METRON_HOME:?:METRON_HOME needs to be set}"

cd $METRON_HOME

echo "cleaning the main project"
mvn clean

cd metron-deployment/

echo "cleaning rpm deployment"
mvn clean -P build-rpms

cd ..
